# Generated by Django 4.2.2 on 2025-09-24 23:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField(help_text='Start of billing period')),
                ('period_end', models.DateTimeField(help_text='End of billing period')),
                ('used', models.IntegerField(default=0, help_text='Number of AI credits used in this billing period')),
                ('allowed', models.IntegerField(help_text='Number of AI credits allowed for this billing period')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
