# Generated by Django 4.2.2 on 2025-02-01 00:11

import django.contrib.postgres.fields
from django.db import migrations, models
import pairdraft.interfaces
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('county', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=200)),
                ('list_price', models.IntegerField(null=True)),
                ('home_owners_association', models.IntegerField(blank=True, null=True)),
                ('hoa_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('annually', 'Annually')], default='monthly', max_length=100)),
                ('description', models.TextField(null=True)),
                ('beds', models.IntegerField(null=True)),
                ('baths', models.IntegerField(null=True)),
                ('sqft', models.IntegerField(null=True)),
                ('year_built', models.IntegerField(null=True)),
                ('lot_size', models.IntegerField(null=True)),
                ('apn', models.CharField(blank=True, max_length=200, null=True)),
                ('home_type', models.CharField(choices=[('single_family', 'Single Family'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('multi_family', 'Multi Family'), ('apartment', 'Apartment'), ('mobile_manufactured', 'Mobile / Manufactured'), ('coop_unit', 'Co-op Unit'), ('vacant_land', 'Vacant Land'), ('other', 'Other')], default='single_family', max_length=100)),
                ('appliances', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('dishwasher', 'Dishwasher'), ('dryer', 'Dryer'), ('freezer', 'Freezer'), ('garbage_disposal', 'Garbage Disposal'), ('microwave', 'Microwave'), ('range_or_oven', 'Range / Oven'), ('refrigerator', 'Refrigerator'), ('trash_compactor', 'Trash Compactor'), ('washer', 'Washer')], max_length=100), blank=True, default=list, size=None)),
                ('public_listing', models.BooleanField(blank=True, default=True, help_text='Whether the property is searchable in Koya')),
                ('photo_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('zpid', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('zillow_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            bases=(models.Model, pairdraft.interfaces.ModelWithFormFields),
        ),
    ]
