import type {EditorThemeClasses} from 'lexical';

import 'public/editor-theme.css';

export const theme: EditorThemeClasses = {
  autocomplete: 'autocomplete',
  blockCursor: 'blockCursor',
  characterLimit: 'characterLimit',
  code: 'code',
  codeHighlight: {
    atrule: 'tokenAttr',
    attr: 'tokenAttr',
    boolean: 'tokenProperty',
    builtin: 'tokenSelector',
    cdata: 'tokenComment',
    char: 'tokenSelector',
    class: 'tokenFunction',
    'class-name': 'tokenFunction',
    comment: 'tokenComment',
    constant: 'tokenProperty',
    deleted: 'tokenProperty',
    doctype: 'tokenComment',
    entity: 'tokenOperator',
    function: 'tokenFunction',
    important: 'tokenVariable',
    inserted: 'tokenSelector',
    keyword: 'tokenAttr',
    namespace: 'tokenVariable',
    number: 'tokenProperty',
    operator: 'tokenOperator',
    prolog: 'tokenComment',
    property: 'tokenProperty',
    punctuation: 'tokenPunctuation',
    regex: 'tokenVariable',
    selector: 'tokenSelector',
    string: 'tokenSelector',
    symbol: 'tokenProperty',
    tag: 'tokenProperty',
    url: 'tokenOperator',
    variable: 'tokenVariable',
  },
  embedBlock: {
    base: 'embedBlock',
    focus: 'embedBlockFocus',
  },
  hashtag: 'hashtag',
  heading: {
    h1: 'h1',
    h2: 'h2',
    h3: 'h3',
    h4: 'h4',
    h5: 'h5',
    h6: 'h6',
  },
  hr: 'hr',
  hrSelected: 'hrSelected',
  image: 'editor-image',
  indent: 'indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'layoutContainer',
  layoutItem: 'layoutItem',
  link: 'link',
  list: {
    checklist: 'checklist',
    listitem: 'listItem',
    listitemChecked: 'listItemChecked',
    listitemUnchecked: 'listItemUnchecked',
    nested: {
      listitem: 'nestedListItem',
    },
    olDepth: [
      'ol1',
      'ol2',
      'ol3',
      'ol4',
      'ol5',
    ],
    ul: 'ul',
  },
  ltr: 'ltr',
  mark: 'mark',
  markOverlap: 'markOverlap',
  paragraph: 'paragraph',
  quote: 'quote',
  rtl: 'rtl',
  specialText: 'specialText',
  tab: 'tabNode',
  table: 'table',
  tableAddColumns: 'tableAddColumns',
  tableAddRows: 'tableAddRows',
  tableAlignment: {
    center: 'tableAlignmentCenter',
    right: 'tableAlignmentRight',
  },
  tableCell: 'tableCell',
  tableCellActionButton: 'tableCellActionButton',
  tableCellActionButtonContainer:
    'tableCellActionButtonContainer',
  tableCellHeader: 'tableCellHeader',
  tableCellResizer: 'tableCellResizer',
  tableCellSelected: 'tableCellSelected',
  tableFrozenColumn: 'tableFrozenColumn',
  tableFrozenRow: 'tableFrozenRow',
  tableRowStriping: 'tableRowStriping',
  tableScrollableWrapper: 'tableScrollableWrapper',
  tableSelected: 'tableSelected',
  tableSelection: 'tableSelection',
  text: {
    bold: 'textBold',
    capitalize: 'textCapitalize',
    code: 'textCode',
    highlight: 'textHighlight',
    italic: 'textItalic',
    lowercase: 'textLowercase',
    strikethrough: 'textStrikethrough',
    subscript: 'textSubscript',
    superscript: 'textSuperscript',
    underline: 'textUnderline',
    underlineStrikethrough: 'textUnderlineStrikethrough',
    uppercase: 'textUppercase',
  },
};