# Generated by Django 4.2.2 on 2025-02-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='signature',
        ),
    ]
