# Generated by Django 4.2.2 on 2025-01-31 20:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('objective', models.CharField(blank=True, max_length=200, null=True)),
                ('executor', models.CharField(blank=True, choices=[('base', 'Base'), ('function', 'Function'), ('question', 'Question'), ('api', 'API'), ('document', 'Document'), ('breakpoint', 'Breakpoint'), ('check', 'Check'), ('file', 'File'), ('set_field', 'Set Field')], default='base', max_length=10, null=True)),
                ('echo_text', models.CharField(blank=True, help_text='Exact text to send to the user.', max_length=200, null=True)),
                ('is_index', models.BooleanField(default=False, help_text='Indicates that this step is an index level step.')),
            ],
        ),
        migrations.CreateModel(
            name='APIStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.step')),
                ('endpoint_path', models.CharField(default='', help_text="Path of the endpoint to execute if executor is 'api'.", max_length=200)),
            ],
            bases=('agent.step',),
        ),
        migrations.CreateModel(
            name='BranchingStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.step')),
                ('condition_slugs', models.JSONField(default=list, help_text='Slugs of the steps that are the conditions for this branching step.')),
                ('function_name', models.CharField(blank=True, help_text="Name of the function to execute if executor is 'check'.", max_length=200, null=True)),
                ('field_name', models.CharField(blank=True, help_text="Name of the field to check if executor is 'check'.", max_length=200, null=True)),
            ],
            bases=('agent.step',),
        ),
        migrations.CreateModel(
            name='ConditionStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.step')),
                ('condition', models.CharField(blank=True, help_text='A condition that must be satisfield for this step to follow a BranchingStep parent step.', max_length=200, null=True)),
            ],
            bases=('agent.step',),
        ),
        migrations.CreateModel(
            name='DocumentStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.step')),
                ('document_slug', models.CharField(blank=True, help_text='Slug of the document for this step, if there is one.', max_length=200, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('field', 'Field'), ('title', 'Title'), ('heading', 'Heading'), ('subheading', 'Subheading'), ('document', 'Document')], default='text', max_length=10)),
                ('text', models.CharField(blank=True, help_text='Text for the document clause, if there is one.', max_length=1000, null=True)),
                ('indent', models.IntegerField(default=0, help_text='Indentation level of the document clause.')),
                ('order', models.CharField(blank=True, help_text='Order prefix for the document clause such as 1. or a. or i. etc.', max_length=20, null=True)),
                ('template', models.CharField(blank=True, help_text='Template for the document clause, if there is one.', max_length=500, null=True)),
                ('field_type', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('multi-checkbox', 'Multi-Checkbox')], default='text', max_length=20, null=True)),
                ('choices', models.JSONField(blank=True, default=list, help_text="Choices for the field type 'select' and 'multi-checkbox'.", null=True)),
                ('trigger_update', models.BooleanField(default=False, help_text='Indicates whether the document should be updated when the field is shown.')),
                ('callback', models.CharField(blank=True, help_text='Name of the function to call when this step is handled.', max_length=200, null=True)),
            ],
            bases=('agent.step',),
        ),
        migrations.CreateModel(
            name='FieldStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.step')),
                ('field_name', models.CharField(help_text='Name of the field (can be nested).', max_length=200)),
            ],
            bases=('agent.step',),
        ),
        migrations.CreateModel(
            name='FileStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.step')),
                ('file_path', models.CharField(help_text='Path of the file containing more steps.', max_length=200)),
            ],
            bases=('agent.step',),
        ),
        migrations.CreateModel(
            name='FunctionStep',
            fields=[
                ('step_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agent.step')),
                ('function_name', models.CharField(default='', help_text="Name of the function to execute if executor is 'function'.", max_length=200)),
            ],
            bases=('agent.step',),
        ),
        migrations.CreateModel(
            name='UserStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(default='', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('state', models.JSONField(default=dict)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.userstep')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.step')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
