# Generated by Django 4.2.2 on 2025-02-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_action_type'),
        ('agent', '0002_alter_userstep_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstep',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersteps', to='documents.document'),
        ),
    ]
