# Generated by Django 4.2.2 on 2025-02-22 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('agent', '0003_alter_userstep_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstep',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersteps', to='users.userprofile'),
        ),
    ]
