# Generated by Django 4.2.2 on 2025-07-25 18:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('documents', '0014_update_submitted_action_type'),
        ('agent', '0004_alter_userstep_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like model version, token count, etc.')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to='documents.document')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_messages', to='users.userprofile')),
                ('user_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_messages', to='agent.userstep')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
