# Generated by Django 4.2.2 on 2025-07-25 18:57

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def migrate_messages_from_userstep(apps, schema_editor):
    UserStep = apps.get_model('agent', 'UserStep')
    AgentMessage = apps.get_model('agent', 'AgentMessage')
    
    # Counter for migration statistics
    total_messages = 0
    skipped_messages = 0
    
    # Get all UserSteps with history in their state
    for user_step in UserStep.objects.exclude(state__isnull=True):
        state = user_step.state or {}
        history = state.get('history', [])
        
        for entry in history:
            if isinstance(entry, str):
                if entry.startswith('[Koya]: '):
                    content = entry[8:]  # Remove "[Koya]: " prefix
                    
                    # Skip metadata entries that start with '{'
                    if content.startswith('{'):
                        skipped_messages += 1
                        continue
                    
                    AgentMessage.objects.create(
                        user_profile=user_step.user_profile,
                        document=user_step.document,
                        user_step=user_step,
                        role='agent',
                        content=content
                    )
                    total_messages += 1
                    
                elif entry.startswith('[Human]: '):
                    content = entry[9:]  # Remove "[Human]: " prefix
                    AgentMessage.objects.create(
                        user_profile=user_step.user_profile,
                        document=user_step.document,
                        user_step=user_step,
                        role='user',
                        content=content
                    )
                    total_messages += 1
                    
                # Skip other formats (plain objects, etc.)
                else:
                    skipped_messages += 1
            else:
                # Skip non-string entries (objects)
                skipped_messages += 1
    
    logger.info(f"Migration complete: {total_messages} messages migrated, {skipped_messages} entries skipped")


def reverse_migration(apps, schema_editor):
    # Delete all migrated messages
    AgentMessage = apps.get_model('agent', 'AgentMessage')
    count = AgentMessage.objects.filter(user_step__isnull=False).count()
    AgentMessage.objects.filter(user_step__isnull=False).delete()
    logger.info(f"Reverse migration: Deleted {count} migrated messages")


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_add_agent_message'),
    ]

    operations = [
        migrations.RunPython(migrate_messages_from_userstep, reverse_migration),
    ]
