# Generated by Django 4.2.2 on 2025-07-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0007_fix_agent_message_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchingstep',
            name='step_ptr',
        ),
        migrations.RemoveField(
            model_name='conditionstep',
            name='step_ptr',
        ),
        migrations.RemoveField(
            model_name='documentstep',
            name='step_ptr',
        ),
        migrations.RemoveField(
            model_name='fieldstep',
            name='step_ptr',
        ),
        migrations.RemoveField(
            model_name='filestep',
            name='step_ptr',
        ),
        migrations.RemoveField(
            model_name='functionstep',
            name='step_ptr',
        ),
        migrations.RemoveField(
            model_name='userstep',
            name='document',
        ),
        migrations.RemoveField(
            model_name='userstep',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='userstep',
            name='step',
        ),
        migrations.RemoveField(
            model_name='userstep',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='agentmessage',
            name='user_step',
        ),
        migrations.DeleteModel(
            name='APIStep',
        ),
        migrations.DeleteModel(
            name='BranchingStep',
        ),
        migrations.DeleteModel(
            name='ConditionStep',
        ),
        migrations.DeleteModel(
            name='DocumentStep',
        ),
        migrations.DeleteModel(
            name='FieldStep',
        ),
        migrations.DeleteModel(
            name='FileStep',
        ),
        migrations.DeleteModel(
            name='FunctionStep',
        ),
        migrations.DeleteModel(
            name='Step',
        ),
        migrations.DeleteModel(
            name='UserStep',
        ),
    ]
