# Generated by Django 4.2.2 on 2025-07-25 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tokens.token')),
                ('email', models.EmailField(max_length=254)),
                ('action', models.CharField(choices=[('login', 'Login'), ('signup', 'Signup')], max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('auth_method', models.CharField(default='magic_link', max_length=20)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            bases=('tokens.token',),
        ),
        migrations.CreateModel(
            name='MagicCodeToken',
            fields=[
            ],
            options={
                'verbose_name': 'Magic Code Token',
                'verbose_name_plural': 'Magic Code Tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tokens.authenticationtoken',),
        ),
        migrations.CreateModel(
            name='PasskeyToken',
            fields=[
            ],
            options={
                'verbose_name': 'Passkey Token',
                'verbose_name_plural': 'Passkey Tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tokens.authenticationtoken',),
        ),
        migrations.CreateModel(
            name='SSOToken',
            fields=[
            ],
            options={
                'verbose_name': 'SSO Token',
                'verbose_name_plural': 'SSO Tokens',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tokens.authenticationtoken',),
        ),
    ]
