# Generated by Django 4.2.2 on 2025-08-19 21:49

from django.db import migrations, models


def update_magic_link_to_magic_code(apps, schema_editor):
    """Update all existing magic_link auth_method values to magic_code"""
    AuthenticationToken = apps.get_model('tokens', 'AuthenticationToken')
    AuthenticationToken.objects.filter(auth_method='magic_link').update(auth_method='magic_code')


def reverse_update(apps, schema_editor):
    """Reverse migration - convert magic_code back to magic_link"""
    AuthenticationToken = apps.get_model('tokens', 'AuthenticationToken')
    AuthenticationToken.objects.filter(auth_method='magic_code').update(auth_method='magic_link')


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_authenticationtoken_magiccodetoken_passkeytoken_and_more'),
    ]

    operations = [
        migrations.RunPython(update_magic_link_to_magic_code, reverse_update),
        migrations.AlterField(
            model_name='authenticationtoken',
            name='auth_method',
            field=models.CharField(default='magic_code', max_length=20),
        ),
    ]
