# Generated by Django 4.2.2 on 2025-08-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_remove_magic_link_auth_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasskeyToken',
        ),
        migrations.DeleteModel(
            name='SSOToken',
        ),
        migrations.RemoveField(
            model_name='authenticationtoken',
            name='auth_method',
        ),
    ]
