# Generated by Django 4.2.2 on 2025-08-21 20:06

from django.db import migrations, models
import django.db.models.deletion


def migrate_codes_to_magic_code_tokens(apps, schema_editor):
    """Create MagicCodeToken records for existing AuthenticationTokens with codes"""
    db_alias = schema_editor.connection.alias
    
    # Since MagicCodeToken inherits from AuthenticationToken via multi-table inheritance,
    # we need to use raw SQL to insert the records properly
    with schema_editor.connection.cursor() as cursor:
        # Create MagicCodeToken records for all AuthenticationTokens that have codes
        cursor.execute("""
            INSERT INTO tokens_magiccodetoken (authenticationtoken_ptr_id, code)
            SELECT token_ptr_id, old_code 
            FROM tokens_authenticationtoken 
            WHERE old_code IS NOT NULL
        """)


def reverse_migration(apps, schema_editor):
    """Delete all MagicCodeToken records"""
    MagicCodeToken = apps.get_model('tokens', 'MagicCodeToken')
    MagicCodeToken.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_remove_auth_method_field'),
    ]

    operations = [
        # First, rename the code field on AuthenticationToken to avoid conflicts
        migrations.RenameField(
            model_name='authenticationtoken',
            old_name='code',
            new_name='old_code',
        ),
        
        # Delete the proxy model
        migrations.DeleteModel(
            name='MagicCodeToken',
        ),
        
        # Create the new concrete MagicCodeToken model with code field
        migrations.CreateModel(
            name='MagicCodeToken',
            fields=[
                ('authenticationtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tokens.authenticationtoken')),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'Magic Code Token',
                'verbose_name_plural': 'Magic Code Tokens',
            },
            bases=('tokens.authenticationtoken',),
        ),
        
        # Migrate data from AuthenticationToken.old_code to MagicCodeToken.code
        migrations.RunPython(
            migrate_codes_to_magic_code_tokens,
            reverse_migration
        ),
        
        # Finally, remove the old_code field from AuthenticationToken
        migrations.RemoveField(
            model_name='authenticationtoken',
            name='old_code',
        ),
    ]