"""
Django settings for pairdraft project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# Check if we're running in production on Railway
IS_RAILWAY_APP = "RAILWAY_ENVIRONMENT" in os.environ
IS_PRODUCTION = IS_RAILWAY_APP

# Set this value to test on mobile
# Additionally, update the value in the 'Run Server - Mobile' run config in launch.json
MOBILE_HOST = None # '192.168.1.31'

# SECURITY WARNING: don't run with debug turned on in production!
if not IS_PRODUCTION:
    DEBUG = True
 
if IS_PRODUCTION:
    ALLOWED_HOSTS = ['.reachagreements.com']
elif MOBILE_HOST:
    ALLOWED_HOSTS = [MOBILE_HOST]
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'users.apps.UsersConfig',
    'properties.apps.PropertiesConfig',
    'agent.apps.AgentConfig',
    'payments.apps.PaymentsConfig',
    'billing.apps.BillingConfig',
    'terms.apps.TermsConfig',
    'tokens.apps.TokensConfig',
    'tasks.apps.TasksConfig',
    'documents.apps.DocumentsConfig',
    'inbox.apps.InboxConfig',
    'waitlist.apps.WaitlistConfig',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pairdraft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pairdraft.wsgi.application'

# Postgres
if IS_PRODUCTION:
    # In production the database configuration is derived from the `DATABASE_URL`
    # environment variable by the dj-database-url package.
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=True,
        ),
    }
else:
    # Database
    # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'pairdraft',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/app/staticfiles/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Daphne
ASGI_APPLICATION = "pairdraft.asgi.application"

# Channels
if IS_PRODUCTION:
    REDIS_HOST = os.environ.get('REDIS_URL')
else:
    REDIS_HOST = 'redis://127.0.0.1:6379'

CHANNEL_LAYERS = { 
    "default": { 
        "BACKEND": "channels_redis.core.RedisChannelLayer", 
        "CONFIG": {
            "hosts": [REDIS_HOST]
        },
    },
}

if IS_PRODUCTION:
    CSRF_TRUSTED_ORIGINS = [
        'https://reachagreements.com',
        'https://www.reachagreements.com',
        'https://api.reachagreements.com',
        'https://yjs.reachagreements.com',
        'https://docs.reachagreements.com'
    ]
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000'
    ]
    if MOBILE_HOST:
        CSRF_TRUSTED_ORIGINS.append(f'http://{MOBILE_HOST}:3000')

if IS_PRODUCTION:
    CORS_ALLOWED_ORIGINS = [
        'https://reachagreements.com',
        'https://www.reachagreements.com',
        'https://api.reachagreements.com',
        'https://yjs.reachagreements.com',
        'https://docs.reachagreements.com'
    ]
else:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000'
    ]
    if MOBILE_HOST:
        CORS_ALLOWED_ORIGINS.append(f'http://{MOBILE_HOST}:3000')

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = (
    *default_headers,
    "Content-Disposition",  # for the file upload endpoint
)

# Security settings for authentication
if IS_PRODUCTION:
    # Production security settings
    # Railway handles SSL termination, so we shouldn't redirect
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # Session security
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_DOMAIN = '.reachagreements.com'  # Enable cookie sharing across all subdomains
    
    # CSRF security
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = False  # Must be False so JavaScript can read it
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_DOMAIN = '.reachagreements.com'  # Enable cookie sharing across all subdomains
else:
    # Development settings
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Additional security headers
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'auth_security': {
            'format': 'AUTH_SECURITY {asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'auth_security_handler': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'auth_security',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'auth_security': {
            'handlers': ['auth_security_handler', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'tokens': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}