# Generated by Django 4.2.2 on 2025-01-31 22:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text/html', 'HTML'), ('application/pdf', 'PDF')], default='text/html', max_length=30)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.text')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('created', 'Created'), ('created_counter', 'Created Counter'), ('created_review', 'Created Review'), ('submitted', 'Submitted'), ('requested_review', 'Requested Review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('countered', 'Countered'), ('reviewed', 'Reviewed'), ('signed', 'Signed')], default='created', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='documents.document')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_from_user', to='users.userprofile')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_to_user', to='users.userprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
