# Generated by Django 4.2.2 on 2025-02-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('create', 'Create'), ('create_counter', 'Create Counter'), ('create_review', 'Create Review'), ('submit', 'Submit'), ('request_review', 'Request Review'), ('accept', 'Accept'), ('decline', 'Decline'), ('counter', 'Counter'), ('review', 'Review'), ('sign', 'Sign')], default='create', max_length=30),
        ),
    ]
