# Generated by Django 4.2.2 on 2025-02-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('create', 'Create'), ('create_counter', 'Create Counter'), ('create_review', 'Create Review'), ('delete', 'Delete'), ('submit', 'Submit'), ('request_review', 'Request Review'), ('accept', 'Accept'), ('decline', 'Decline'), ('sign', 'Sign')], default='create', max_length=30),
        ),
    ]
