# Generated by Django 4.2.2 on 2025-03-06 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content_type',
        ),
    ]
