# Generated by Django 4.2.2 on 2025-03-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='abcde', max_length=5),
            preserve_default=False,
        ),
    ]
