# Generated by Django 4.2.2 on 2025-03-11 01:04

from django.db import migrations, models
import django.db.models.deletion


def set_default_thread(apps, schema_editor):
    """Set default thread for existing comments."""
    Comment = apps.get_model('documents', 'Comment')
    Thread = apps.get_model('documents', 'Thread')
    Document = apps.get_model('documents', 'Document')
    
    # For each comment without a thread, create or find a thread
    comments_without_thread = Comment.objects.filter(thread__isnull=True)
    
    for comment in comments_without_thread:
        # Try to find an existing thread for the document, or create one
        # Note: We need to determine which document this comment belongs to
        # Since the original model doesn't show document relationship on Comment,
        # we'll create a default thread for now
        if hasattr(comment, 'document'):
            document = comment.document
        else:
            # If no document relationship, get the first document or create one
            document = Document.objects.first()
            if not document:
                continue  # Skip if no documents exist
        
        thread, created = Thread.objects.get_or_create(
            document=document,
            defaults={'resolved': False}
        )
        
        comment.thread = thread
        comment.save()


def reverse_set_default_thread(apps, schema_editor):
    """Reverse operation - no action needed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.thread'),
        ),
        migrations.RunPython(set_default_thread, reverse_set_default_thread),
        migrations.AlterField(
            model_name='comment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.thread'),
        ),
    ]
