# Generated by Django 4.2.2 on 2025-03-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_comment_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
    ]
