# Generated by Django 4.2.2 on 2025-03-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_remove_comment_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='thread_id',
        ),
    ]
