# Generated by Django 4.2.2 on 2025-07-25

from django.db import migrations


def update_created_to_create(apps, schema_editor):
    """Update all 'created' action types to 'create'"""
    Action = apps.get_model('documents', 'Action')
    Action.objects.filter(type='created').update(type='create')


def revert_create_to_created(apps, schema_editor):
    """Revert 'create' action types back to 'created'"""
    Action = apps.get_model('documents', 'Action')
    Action.objects.filter(type='create').update(type='created')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_thread_thread_id'),
    ]

    operations = [
        migrations.RunPython(update_created_to_create, revert_create_to_created),
    ]