# Generated by Django 4.2.2 on 2025-07-25

from django.db import migrations


def update_submitted_to_submit(apps, schema_editor):
    """Update all 'submitted' action types to 'submit'"""
    Action = apps.get_model('documents', 'Action')
    Action.objects.filter(type='submitted').update(type='submit')


def revert_submit_to_submitted(apps, schema_editor):
    """Revert 'submit' action types back to 'submitted'"""
    Action = apps.get_model('documents', 'Action')
    Action.objects.filter(type='submit').update(type='submitted')


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_update_created_action_type'),
    ]

    operations = [
        migrations.RunPython(update_submitted_to_submit, revert_submit_to_submitted),
    ]