# Generated by Django 4.2.2 on 2025-01-31 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pairdraft.interfaces
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('google_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('photo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_attorney', models.BooleanField(blank=True, default=False, help_text='Whether this user is an attorney', verbose_name='Is Attorney')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to='users.userprofile')),
                ('offers', models.BooleanField(blank=True, default=True, help_text='New offers, accepted offers, rejected offers, and other actions taken on offers', verbose_name='Offers')),
                ('messages', models.BooleanField(blank=True, default=True, help_text='New or unread messages from buyers or sellers', verbose_name='Messages')),
                ('actions', models.BooleanField(blank=True, default=True, help_text='Action due dates, reminders, and other notifications', verbose_name='Actions')),
                ('product_news', models.BooleanField(blank=True, default=True, help_text='New features and other product improvements', verbose_name='Product News')),
                ('resources', models.BooleanField(blank=True, default=True, help_text='New blog posts and product guides', verbose_name='Resources')),
                ('attorney_mode', models.BooleanField(blank=True, default=False, help_text='Value is used to toggle between attorney and buyer/seller mode in dashboard.  Only used when user_profile.is_attorney is True.', verbose_name='Attorney Mode')),
            ],
            bases=(models.Model, pairdraft.interfaces.ModelWithFormFields),
        ),
    ]
