# Generated by Django 4.2.2 on 2025-09-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for billing', max_length=255, null=True),
        ),
    ]
