# Generated by Django 4.2.2 on 2025-10-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_stripe_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='attorney_mode',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='preferences',
            name='offers',
        ),
    ]
